return function()
  Extensions.Register("constant",1,1,"Constants")
  RESET_STANDARD=0x1fe0000
  CARD_POLYMERIZATION=24094653
  CATEGORY_HAND_SEARCH=CATEGORY_TOHAND+CATEGORY_SEARCH
  DECK_ORDER_TOP=0
  DECK_ORDER_BOTTOM=1
  DECK_ORDER_SHUFFLE=2
  NO_COPY_NO_DISABLE=EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE
end
